docs: wallet endpoint
wall-ety/wall-ety-api pull request #4
Opened 2024-03-19 15:57 UTC by tsanta-niaina-MT

2024-03-19 20:20 UTC, sanda03 reviewed
you forgot the table "category"

2024-03-20 03:55 UTC, RickaPrincy requested changes
All put or post should have a request body  (make the request body an array)

2024-03-20 03:55 UTC, RickaPrincy commented on doc/api.yml
> +  /Account:
all path must be in lowercase 
ex:  this is wrong  /Account/{AccountId})

2024-03-20 03:55 UTC, RickaPrincy commented on doc/api.yml
> +      operationId: crupdateAccount
Make all crupdate requestBody an Array

2024-03-20 03:55 UTC, RickaPrincy commented on doc/api.yml
> +  /Transaction:
transactions
Make them in plural 

/accounts
/transactions
...

2024-03-20 03:55 UTC, RickaPrincy commented on doc/api.yml
> +      operationId: CreateOrUpdateTransaction
missing requestBody

2024-03-20 03:55 UTC, RickaPrincy commented on doc/api.yml
> +      operationId: CreateOrUpdateTransfert
missing request body

2024-03-20 03:55 UTC, RickaPrincy commented on doc/api.yml
> +  /balance_history:
balances

2024-03-20 17:46 UTC, merged